# Generated by Django 3.1.7 on 2021-05-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_index'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='index',
            new_name='index1',
        ),
    ]
