# Generated by Django 3.1.7 on 2021-05-24 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0005_auto_20210523_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index1',
        ),
    ]
